version: '3.8'

services:
  app:
    build: .
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - PORT=5002
      - MONGODB_URI=mongodb+srv://itzvellodan:mVRHqdTyBU8Q5igL@solarerp.nb5ij.mongodb.net/?retryWrites=true&w=majority&appName=solarerp
      - JWT_SECRET=692cb33671b08ed48e58c5a70696b5cdc3038b8b919af6a83792541b1c507203df53c7ba89b3e3f5f13ae695a3a7ed608ea49a2cc111cef99d6120867553276d
      - JWT_EXPIRES_IN=7d
      - ADMIN_EMAIL=admin@solarerp.com
      - ADMIN_PASSWORD=Admin@123
      - ADMIN_FIRST_NAME=Admin
      - ADMIN_LAST_NAME=User
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
