version: '3.8'

services:
  app:
    build: .
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - PORT=5002
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
      - ADMIN_EMAIL=admin@solarerp.com
      - ADMIN_PASSWORD=Admin@123
      - ADMIN_FIRST_NAME=Admin
      - ADMIN_LAST_NAME=User
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
